export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const START_FETCHING_USERS = 'START_FETCHING_USERS';
export const STOP_FETCHING_USERS = 'STOP_FETCHING_USERS';
