export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_BASKET_SUCCESS = 'FETCH_BASKET_SUCCESS';
export const FETCH_BASKET = 'FETCH_BASKET';
export const GRAB_APPLE = 'GRAB_APPLE';
export const FREE_ALL_APPLES = 'FREE_ALL_APPLES';
export const DISPLAY_ERROR_MESSAGE = 'DISPLAY_ERROR_MESSAGE';
